USE `Films`;

CREATE TABLE `film_users` (
                         `identity` INTEGER NOT NULL AUTO_INCREMENT,
                         `login` VARCHAR(255) NOT NULL UNIQUE,
                         `password` CHAR(32) NOT NULL,
    /*
     * 0 - администратор (Role.ADMINISTRATOR)
     * 1 - пользователь (Role.USER)
     * 2 - гость (Role.GUEST)
     */
                         `role` TINYINT NOT NULL CHECK (`role` IN (0, 1, 2)),
                         PRIMARY KEY (`identity`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 22:43:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8 ;
USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `year` INT NOT NULL,
    `image_url` VARCHAR(255) NOT NULL,
    `runtime` INT NOT NULL,
    `budget` INT NOT NULL,
    `gross` INT NOT NULL,
    `rating` FLOAT NOT NULL,
    `description` TEXT NOT NULL,
    `votes` INT NOT NULL,
     PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`directors` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `about` TEXT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`stars` (
     `id` INT NOT NULL AUTO_INCREMENT,
     `name` VARCHAR(45) NOT NULL,
     `about` TEXT NULL,
     PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`genres` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_directors` (
      `movies_id` INT NOT NULL,
      `directors_id` INT NOT NULL,
      PRIMARY KEY (`movies_id`, `directors_id`),
      INDEX `fk_movies_has_directors_directors1_idx` (`directors_id` ASC) VISIBLE,
      INDEX `fk_movies_has_directors_movies_idx` (`movies_id` ASC) VISIBLE,
      CONSTRAINT `fk_movies_has_directors_movies`
          FOREIGN KEY (`movies_id`)
              REFERENCES `movies_db`.`movies` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION,
      CONSTRAINT `fk_movies_has_directors_directors1`
          FOREIGN KEY (`directors_id`)
              REFERENCES `movies_db`.`directors` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_stars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_stars` (
      `movies_id` INT NOT NULL,
      `stars_id` INT NOT NULL,
      PRIMARY KEY (`movies_id`, `stars_id`),
      INDEX `fk_movies_has_stars_stars1_idx` (`stars_id` ASC) VISIBLE,
      INDEX `fk_movies_has_stars_movies1_idx` (`movies_id` ASC) VISIBLE,
      CONSTRAINT `fk_movies_has_stars_movies1`
          FOREIGN KEY (`movies_id`)
              REFERENCES `movies_db`.`movies` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION,
      CONSTRAINT `fk_movies_has_stars_stars1`
          FOREIGN KEY (`stars_id`)
              REFERENCES `movies_db`.`stars` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_genres` (
      `movies_id` INT NOT NULL,
      `genres_id` INT NOT NULL,
      PRIMARY KEY (`movies_id`, `genres_id`),
      INDEX `fk_movies_has_genres_genres1_idx` (`genres_id` ASC) VISIBLE,
      INDEX `fk_movies_has_genres_movies1_idx` (`movies_id` ASC) VISIBLE,
      CONSTRAINT `fk_movies_has_genres_movies1`
          FOREIGN KEY (`movies_id`)
              REFERENCES `movies_db`.`movies` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION,
      CONSTRAINT `fk_movies_has_genres_genres1`
          FOREIGN KEY (`genres_id`)
              REFERENCES `movies_db`.`genres` (`id`)
              ON DELETE NO ACTION
              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`users` (
      `id` INT NOT NULL AUTO_INCREMENT,
      `login` VARCHAR(45) NOT NULL,
      `pasword` VARCHAR(45) NOT NULL,
      `email` VARCHAR(32) NOT NULL,
      `registrationdate` DATE NOT NULL,
/*
* 0 - администратор (Role.ADMINISTRATOR)
* 1 - модератор (Role.MODERATOR)
* 2 - пользователь (Role.USER)
* 3 - гость (Role.GUEST)
*/

      `role` TINYINT NOT NULL CHECK (`role` IN (0, 1, 2)),
      PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`roles` (
    `id` TINYINT NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    `users_id` INT NOT NULL,
    PRIMARY KEY (`id`, `users_id`),
    INDEX `fk_roles_users1_idx` (`users_id` ASC) VISIBLE,
    CONSTRAINT `fk_roles_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `movies_db`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
