USE `Films`;

CREATE TABLE `film_users` (
                         `identity` INTEGER NOT NULL AUTO_INCREMENT,
                         `login` VARCHAR(255) NOT NULL UNIQUE,
                         `password` CHAR(32) NOT NULL,
    /*
     * 0 - администратор (Role.ADMINISTRATOR)
     * 1 - пользователь (Role.USER)
     * 2 - гость (Role.BANNED)
     */
                         `role` TINYINT NOT NULL CHECK (`role` IN (0, 1, 2)),
                         PRIMARY KEY (`identity`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 22:43:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8 ;
USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `year` INT NOT NULL,
    `image_path` VARCHAR(255) NOT NULL,
    `runtime` INT NOT NULL,
    `budget` INT NOT NULL,
    `gross` INT NOT NULL,
    `description` TEXT NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`genres` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_genres` (
    `movies_id` INT NOT NULL,
    `genres_id` INT NOT NULL,
    PRIMARY KEY (`movies_id`, `genres_id`),
    INDEX `fk_movies_has_genres_genres1_idx` (`genres_id` ASC) VISIBLE,
    INDEX `fk_movies_has_genres_movies1_idx` (`movies_id` ASC) VISIBLE,
    CONSTRAINT `fk_movies_has_genres_movies1`
        FOREIGN KEY (`movies_id`)
           REFERENCES `movies_db`.`movies` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_movies_has_genres_genres1`
        FOREIGN KEY (`genres_id`)
            REFERENCES `movies_db`.`genres` (`id`)
            ON DELETE NO ACTION)    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(45) NOT NULL,
    `password` NCHAR(255) NULL,
    `email` VARCHAR(32) NOT NULL,
    `role` TINYINT NOT NULL,
    `registrationdate` DATE NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`participants` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `surname` VARCHAR(45) NOT NULL,
    `secondname` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_participants` (
    `movies_id` INT NOT NULL,
    `participants_id` INT NOT NULL,
    `position` INT NOT NULL,
    PRIMARY KEY (`movies_id`, `participants_id`),
    INDEX `fk_movies_has_actors_or_directors_actors_or_directors1_idx` (`participants_id` ASC) VISIBLE,
    INDEX `fk_movies_has_actors_or_directors_movies1_idx` (`movies_id` ASC) VISIBLE,
    CONSTRAINT `fk_movies_has_actors_or_directors_movies1`
        FOREIGN KEY (`movies_id`)
            REFERENCES `movies_db`.`movies` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_movies_has_actors_or_directors_actors_or_directors1`
        FOREIGN KEY (`participants_id`)
           REFERENCES `movies_db`.`participants` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`movies_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies_users` (
    `users_id` INT NOT NULL,
    `date` DATE NOT NULL,
    `movies_id` INT NOT NULL,
    PRIMARY KEY (`users_id`),
    INDEX `fk_movies_has_users_users1_idx` (`users_id` ASC) VISIBLE,
    INDEX `fk_movies_users_movies1_idx` (`movies_id` ASC) VISIBLE,
    CONSTRAINT `fk_movies_has_users_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `movies_db`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_movies_users_movies1`
        FOREIGN KEY (`movies_id`)
            REFERENCES `movies_db`.`movies` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


-- -----------------------------------------------------
-- Table `movies_db`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`vote` (
   `score` INT NOT NULL,
   `date` DATE NOT NULL,
   `users_id` INT NOT NULL,
   `movies_id` VARCHAR(45) NOT NULL,
   PRIMARY KEY (`users_id`),
   CONSTRAINT `fk_votes_users1`
       FOREIGN KEY (`users_id`)
           REFERENCES `movies_db`.`users` (`id`)
           ON DELETE NO ACTION
           ON UPDATE NO ACTION)
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;